config/routes.rb
Rails.application.routes.draw do

  root 'pages#prez'
  get 'fourchette' => 'pages#fourchette', as: :fourchette
  get 'grelinette' => 'pages#grelinette', as: :grelinette
  get 'nous' => 'pages#nous' , as: :nous

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def grelinette
  end

  def fourchette
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GrelinetteFourchette</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'shared/navbar' %>
<%= yield %>
</body>
</html>

app/views/pages/fourchette.html.erb
<% provide(:fourchette, "active") %>
<% provide(:logo_la_haut, "logo_clem.jpg") %>

   <!-- Main jumbotron for a primary marketing message or call to action -->
   
    <div class="head_clem">
	<div class="text-vertical-center">
		<h1 class="text-vertical-center"> Un foodtruck qu'il est bien </h1>
	</div>
    </div>

    <div class="content_a">
      <!-- Example row of columns -->
      <div class="container">	
      <div class="row">
   
        <div class="col-md-4">
    <%= image_tag("logo_clem.jpg", class:"img-circle img_descr") %>
          <h2>Une cuisine bio et locale. </h2>
          <p>Nos légumes sont cultivés juste à côté de chez vous, par Adrien dans son champ pas très loin blablabla. Je propose des petits plats bio et sans gluten, végétariens ou non. </p> 
        </div>
        <div class="col-md-4">
   
    <%= image_tag("logo_clem.jpg", class:"img-circle img_descr") %>
          <h2>Un foodtruck en or massif</h2>
          <p>Dans mon foodtruck flambant neuf, je me déplace dans tout le Roannais. Que ce soit pour un festival, un mariage, animer un événement ou juste enrichir les papilles de vos invités, c'est toujours bien d'avoir un foodtruck dans son jardin.    </p>
       </div>
        <div class="col-md-4">
    <%= image_tag("logo_clem.jpg", class:"img-circle img_descr") %>
   
          <h2>A la portée de tous</h2>
        <p> Je me rémunère en vendant de la nourriture à vos invités, l'idée est de rendre la bonne cuisine accessible à tous. Comptez 8 euros pour un menu et 5 euros pour un plat simple ! </p>
	</div>
      </div>
   </div>   
  </div>
   
   <div class="content_b">   
   <div class="container"> 
 	   <div class="row">
       		 <div class="col-md-4">
	 		 <h4> contact : </h4>
	  		<p> Clémentine Chaffal
              		<br>
           		  3 rue machin <br> 98220 Roanne </p>
          		<ul class="list-unstyled">
			<li><i class="fa fa-phone fa-fw"></i> 01 32 56 25 15</li>
			<li><i class=" fa fa-envelope-o fa-fw"></i><a href="mailto:clementine.truc@machin.com">clementine.truc@machin.com</a></li>
                	<li><a href="facebook.com"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
	  		</ul>	
        	</div>
	</div>
    </div>
    </div>

    <div class="map">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d44309.46279791102!2d4.044848391064228!3d46.0442877025844!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f40f40e919ff33%3A0x4093cafcbe80d40!2s42300+Roanne!5e0!3m2!1sfr!2sfr!4v1473321784596" width="100%" height="100%" frameborder="0" style="border:0"></iframe>
    </div>
   

    <div class="container">
	<hr>
	<footer>
	<p> De la grelinette à la fourchette </p>
	</footer>
    </div> <!-- /container -->

app/views/pages/grelinette.html.erb
<% provide(:grelinette, "active") %>
<% provide(:logo_la_haut, "logo_adrien.jpg") %>
 
   <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="head_adri">
    </div>
	
    <div class="content_a">
    <div class="container">
      <!-- Example row of columns -->
      <div class="row">
        <div class="col-md-4">
          <h2>Une cuisine bio et locale. </h2>
          <p>Nos légumes sont cultivés juste à côté de chez vous, par Adrien dans son champ pas très loin blablabla. Je propose des petits plats bio et sans gluten, végétariens ou non. </p>
        </div>

	<div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       </div>
        
	<div class="col-md-4">
          <h2>Heading</h2>
          <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
      	</div>
      </div>
     </div>
      
	<hr>
      <footer>
	<p>De la grelinette à la fourchette</p>
      </footer>
    </div> <!-- /container -->

app/views/pages/nous.html.erb
<% provide(:nous , "active") %>
<h1>Pages#nous</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/prez.html.erb
<% provide(:prez , "active") %>
<h1>Pages#prez</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/shared/_navbar.html.erb
<div class="row">
<div class="logoContain text-center">
	<%= image_tag(yield(:logo_la_haut), class: "logo") %>
	<!-- %= image_tag(yield(:_logo), class: "logo") %> -->
 </div>
</div>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Collect the nav links, forms, and other content for toggling -->
      <ul class="nav navbar-nav">
	<li class="<%= yield(:fourchette)%>"><%= link_to "La cantine de Clémentine", fourchette_path %></li>
        <li class="<%= yield(:grelinette)%>"><%= link_to "Les légumes d'Adrien", grelinette_path %></li>
      </ul>
  </div><!-- /.container-fluid -->
</nav>